sudo: required
dist: trusty
language: scala
scala:
  - 2.11.6
branches:
  only:
    - master
script:
  # run reach-exe tests only by deactivating aggregation
  - sbt "set aggregate in test := false" test
  - sbt main/test
  - sbt assembly/test
  - sbt export/test
